# Generated by Django 3.1.5 on 2021-10-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='isim',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
