# Generated by Django 3.1.5 on 2021-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211025_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='isim',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='kategorimodel',
            table='blog_kategorimodel',
        ),
    ]
