# Generated by Django 3.1.5 on 2021-10-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncellenme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
